### ISSUE TITLE
Script upgrade suggestion

### ISSUE THREAD

**Issue by mati4458** [shiflux/PyViresWithdrawVesting#1]
Hello,
Script is working flawlessly, but due to current Vires LP tokens imports limits it's almost impossible to import VIRES_USDC_LP tokens, would you consider adding this functionality?

**Comment by shiflux** [comment]
Added a simple function that will try periodically to import USDTLP or USDCLP.

I'm not going to implement and check if the function will fail for now. This must be used only for a short period of time or it will burn all waves in fees.

Also now for withdrawing -w option must be used.

**Comment by mati4458** [comment]
Thanks a lot for a quick implementation and reply :)

I have prepared simple script to avoid fees burning. It will only execute, when import and USDN vesting limits are reset so every  block_height % 1440 = 0. Could you add it to the solution, please?


> import requests
> import re
> import time
> 
> api_url = "https://nodes.wavesnodes.com/blocks/height"  # get block height from API
> i = 0
> 
> while True:
> 
>     response = requests.get(api_url)
>     height_str = str(response.json())  # convent value to string
>     height = int(re.search(r'\d+', height_str).group())  # extract int from string
> 
>     if (height%1440==0): #limit reset is occuring when block_height % 1440 = 0
> 
>         #USDCLP, USDTLP import and/or USDN withdrawals to be added here
> 
>         i = i + 1 #count transactions made
> 
>         if i > 4: #limit transactions sent to 5
>             time.sleep(60)
>             i = 0
> 
>     if (height % 1440<1438): # slower refresh rate, when we are far from limit reset
>         time.sleep(60)
